### PR TITLE
Feature.quaternion

### PR DESCRIPTION
**Pull request by bjornborg**
Added a message featuring sensor quaternion readings
It follows this notation:
https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
and is a useful method handling rotation and state-space representation (compared to Euler angles).

### CODE REVIEW

**Review by chrberger — APPROVED** [review]
LGTM, 1052 is not taken?

**Comment by bjornborg** [comment]
I did a quick search in the list, it seems to be free.

**Comment by bjornborg** [comment]
@olbender Could you release a new version merging this branch and other feature asap? I would like to update new microservices in kiwi.

**Comment by olbender** [comment]
No. This cannot be accepted.

**Comment by chrberger** [comment]
@olbender for documentation: we need an explanation in this thread as well

**Pull request closed without merging**
